### ISSUE TITLE
Abort task!

### ISSUE THREAD

**Issue by ekkimosi** [r00t-3xp10it/morpheus#13]
Hi, when I start moroheus on kali 2017.1, no banner pop up and for any kind of filter I try, no response and I receive "abort task".

**Comment by r00t-3xp10it** [comment]
This way i can not help you ..
**i need screenshots of the bug, to understand whats appening in your distro ..**

**Comment by ekkimosi** [comment]
Sorry but it's not possible because actually I'm on ParrotOs and morpheus works very good. 
On latest Kali, starts normally but no pop up and when I try one of the tasks, terminal give me [X] Abort task! 
and exit.

**Comment by r00t-3xp10it** [comment]
ok then ...
maybee its a bad Kali configuration..
no problem ..

iam going to close this isue them ..

**Comment by ekkimosi** [comment]
![img_8892](https://user-images.githubusercontent.com/22117676/26881811-d9a68424-4b98-11e7-9ef6-b7ae2f5afd34.JPG)
![img_8893](https://user-images.githubusercontent.com/22117676/26881810-d95b5b7a-4b98-11e7-86db-c530465fc25f.JPG)

**Comment by ekkimosi** [comment]
New installation from scratch of kali 2017.2. 
Same problem

**Comment by asderm12** [comment]
Same problem // OS: Ubuntu server 17.04 x86
