### ISSUE TITLE
[X] Abort Tasks!

### ISSUE THREAD

**Issue by ekkimosi** [r00t-3xp10it/morpheus#14]
Hi, when I start morpheus on **kali 2017.1**,
no banner pop up and for any kind of filter I try, no response and I receive "**abort task**".

PS: I made a **new installation from scratch of kali**. Same problem. 
![img_8891](https://user-images.githubusercontent.com/22117676/26881926-33077ac8-4b99-11e7-9777-45f7b3e65138.JPG)
![img_8893](https://user-images.githubusercontent.com/22117676/26881927-333856d4-4b99-11e7-8c12-2b6fc570feb9.JPG)

**Comment by r00t-3xp10it** [comment]
Question..
do you have **zenity** installed and working?

Example of **zenity** working ..
![fix](http://1.1m.yt/aw9rxk.png)
**HINT:** The **abort message** appers when we press **No**
but in your case i belive the zenity windows does not apper ?

<br />

Check **line 684**, if **No** its pressed then the module execution will **jump** to the **abort funtion**..
But if **zenity** its not installed, the result its the same (response=0 == abort module execution)
![fix](http://4.1m.yt/-7oeR57.png)

<br />

I have try just now the same option in my **Kali 2.0** (working)
![fix](http://2.1m.yt/1QqiQIv.png)

<br />

## List of tool dependencies:
Please check if all back-end applications (dependencies) are installed ..
https://github.com/r00t-3xp10it/morpheus#dependencies

**Comment by ekkimosi** [comment]
I feel myself so dumb...
**Zenity not installed was the mistake.** 
Many thnx for fast response and for this nice software.
