### ISSUE TITLE
Add sslstrip2 to get around HSTS

### ISSUE THREAD

**Issue by shehzade** [r00t-3xp10it/morpheus#16]
Hey guys i think it would be excellent if you added sslstrip2 to the traffic redirect modules so we could infect browsers such ass chrome and Firefox, just a suggestion though im sure we would be very grateful if implemented.

**Comment by r00t-3xp10it** [comment]
maybee one day i will return to this project (develop) ..
and in that day .. sslstrip2 will be a good adiction ..
have fun ..
