### ISSUE TITLE
DNS Spoof SSL Websites

### ISSUE THREAD

**Issue by talal2** [r00t-3xp10it/morpheus#17]
I Don't what i did wrong, but he only spoof websites that dsnt have HTTPS certificate .

                           Thanks in advance ;) :)

**Comment by r00t-3xp10it** [comment]
explain better ..
because **dns_spoof** works well under https (spoofing) the problem does not reside in that funtionality..
but describe your error for me to understand better whats appening ..

**Comment by r00t-3xp10it** [comment]
tell me what option its giving the error ..
**hint: [screenshots are a good way to report errors ]**

also see this: [video](https://www.youtube.com/watch?v=Su9ZUiGlKnA)
