### ISSUE TITLE
sslstrip query

### ISSUE THREAD

**Issue by usama7628674** [r00t-3xp10it/morpheus#20]
Morpheus has sslstrip not sslstrip+.Any reason not to include ssltrip+.
How about implementing dnschef as dnsproxy is slow and most of the sites don't open properly using dns2proxy.

**Comment by r00t-3xp10it** [comment]
hey man ..stop giving me work ...
ok.. i will take that in consideration in next review

**and let's be honest .. this is not one attack framework ..neigther its intent to be ..**
