### ISSUE TITLE
 Warning: Tried to connect to session manager, None of the authentication protocols specified are supported 

### ISSUE THREAD

**Issue by Matin47** [r00t-3xp10it/morpheus#22]
help please

**Comment by r00t-3xp10it** [comment]
i need at least one **screenshot** of the bug
and the contents of the **setting** file to better understand whats appening ..

**Comment by Matin47** [comment]
Dear sir or medam
Thanks for the support
I have been solved it allready
You can close my case.
Greetings Matin47

**Comment by Mutembei2016** [comment]
How do I solve it

**Comment by baptistedftn** [comment]
How do I solve it ?
