### ISSUE TITLE
Morpheus "Aborting Tasks"

### ISSUE THREAD

**Issue by Pr0t0b0t** [r00t-3xp10it/morpheus#24]
Today i installed Morpheus uisng this link [https://github.com/r00t-3xp10it/morpheus.git](url) after installing when i launch it and choose an options morpheus abort tasks and restart
 Please Need your help to fix this....!!!
Working on ParrotSec under KDE desktop

**Comment by r00t-3xp10it** [comment]
it seems that you dont have installed all dependencies needed ..
**zenity** -> [install zenity on parrot](http://installion.co.uk/parrot/jollyroger/main/z/zenity/install/index.html)
Also.. screenshots are a good way to report bugs, because i can see whats appenning in terminal prompt..
