### ISSUE TITLE
FATAL: ARP poisoning needs a non empty hosts list.

### ISSUE THREAD

**Issue by Chaxiraxi** [r00t-3xp10it/morpheus#25]
When i clone a webpage and inject a JavaScript Keylogger into them, morpheus launch ettercap. But ettecrap return me an error: FATAL: ARP poisoning needs a non empty hosts list. Why ? Someone can help me ?

**Comment by r00t-3xp10it** [comment]
I bet you dont have installed **'[zenity](https://en.wikipedia.org/wiki/Zenity)'** dependencie ..

- 1º Check if you have zenity installed
  `zenity --version` 
- 2º install zenity 
  `sudo apt-get install zenity`

Manual Install: https://help.gnome.org/users/zenity/
#### Remark: One screenshot its allways a good way for me to identify the error ..

**Comment by Chaxiraxi** [comment]
Thanks for your reply. I found the solution, and the problem wasn't zenity, but it was ettercap. I just updates my system and it works.

**Comment by r00t-3xp10it** [comment]
Aaaa my mistake ..
This comment does not belong here ( zenity ) ..
